"""Controllable Voice Cloning panel."""

from __future__ import annotations

import tkinter.filedialog as fd

import customtkinter as ctk

from app.core.audio_player import AudioPlayer
from app.core.tts_engine import TTSEngine
from app.ui.panels.base_panel import GeneratorPanel
from app.utils.config_manager import ConfigManager
from app.utils.i18n import t


_EXAMPLE_TEXT = "This is a cloned voice generated by VoxCPM2 Studio."
_STYLE_EXAMPLES = [
    "(slightly faster, cheerful tone)",
    "(slower, solemn tone)",
    "(whispering, intimate)",
    "(excited, fast-paced)",
    "(sad, quiet)",
    "(reading news, neutral)",
]


class CloningPanel(GeneratorPanel):
    """
    Mode 3 — Controllable Voice Cloning.

    Clone any voice from a short reference WAV clip.  Optionally add style
    guidance (emotion, pace, expression) embedded as a parenthesised prefix.
    """

    def __init__(
        self,
        master: ctk.CTkBaseClass,
        *,
        engine: TTSEngine,
        player: AudioPlayer,
        config: ConfigManager,
        status_cb,
        **kwargs: object,
    ) -> None:
        super().__init__(
            master,
            title=t("clone.title"),
            mode="clone",
            engine=engine,
            player=player,
            config=config,
            status_cb=status_cb,
            **kwargs,
        )

    def _build_input_section(self) -> None:
        f = self._input_frame
        f.grid_columnconfigure(0, weight=1)

        # ── Reference audio ───────────────────────────────────────────────────
        self._lbl(f, t("clone.ref_label")).grid(
            row=0, column=0, padx=24, pady=(0, 4), sticky="w"
        )

        ref_row = ctk.CTkFrame(f, fg_color="transparent")
        ref_row.grid(row=1, column=0, padx=24, pady=(0, 4), sticky="ew")
        ref_row.grid_columnconfigure(0, weight=1)

        self._ref_path = ctk.CTkEntry(
            ref_row,
            height=36,
            placeholder_text=t("clone.ref_placeholder"),
            font=ctk.CTkFont(size=12),
        )
        self._ref_path.grid(row=0, column=0, sticky="ew", padx=(0, 8))

        ctk.CTkButton(
            ref_row,
            text=t("clone.browse"),
            width=84,
            height=36,
            command=self._browse_ref,
        ).grid(row=0, column=1)

        ctk.CTkLabel(
            f,
            text=t("clone.ref_tip"),
            font=ctk.CTkFont(size=11),
            text_color="#667788",
            anchor="w",
        ).grid(row=2, column=0, padx=24, pady=(0, 10), sticky="w")

        # ── Style control (optional) ──────────────────────────────────────────
        style_hdr = ctk.CTkFrame(f, fg_color="transparent")
        style_hdr.grid(row=3, column=0, padx=24, pady=(0, 4), sticky="ew")
        style_hdr.grid_columnconfigure(0, weight=1)

        self._lbl(style_hdr, t("clone.style_label")).grid(
            row=0, column=0, sticky="w"
        )

        self._style_var = ctk.StringVar(value=t("clone.style_examples"))
        ctk.CTkComboBox(
            style_hdr,
            variable=self._style_var,
            values=_STYLE_EXAMPLES,
            width=200,
            command=self._on_style_select,
        ).grid(row=0, column=1)

        self._style = ctk.CTkEntry(
            f,
            height=36,
            placeholder_text=t("clone.style_placeholder"),
            font=ctk.CTkFont(size=12),
        )
        self._style.grid(row=4, column=0, padx=24, pady=(0, 10), sticky="ew")

        # ── Text to synthesise ────────────────────────────────────────────────
        self._lbl(f, t("clone.text_label")).grid(
            row=5, column=0, padx=24, pady=(0, 4), sticky="w"
        )

        self._text = self._textbox(f, height=100)
        self._text.grid(row=6, column=0, padx=24, sticky="ew")
        self._text.insert("0.0", _EXAMPLE_TEXT)

    def _get_gen_kwargs(self) -> dict:
        ref = self._ref_path.get().strip()
        if not ref:
            raise ValueError(t("clone.error_no_ref"))

        text = self._text.get("1.0", "end").strip()
        if not text:
            raise ValueError(t("clone.error_no_text"))

        style = self._style.get().strip()
        if style and not style.startswith("("):
            style = f"({style})"

        full_text = f"{style}{text}" if style else text

        return {
            "text": full_text,
            "reference_wav_path": ref,
        }

    def _browse_ref(self) -> None:
        path = fd.askopenfilename(
            title=t("clone.browse_ref_title"),
            filetypes=[("WAV files", "*.wav"), ("All audio files", "*.wav *.flac *.mp3"), ("All files", "*.*")],
        )
        if path:
            self._ref_path.delete(0, "end")
            self._ref_path.insert(0, path)

    def _on_style_select(self, value: str) -> None:
        if value and "…" not in value:
            self._style.delete(0, "end")
            self._style.insert(0, value)
